apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: nats
spec:
  selector:
    app.kubernetes.io/name: nats
  ports:
    - protocol: TCP
      name: client
      port: 4222
      targetPort: 4222
    - protocol: TCP
      name: leaf
      port: 7422
      targetPort: 7422
    - protocol: TCP
      name: monitor
      port: 8222
      targetPort: 8222
