//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The EdgeFarm Authors.

Licensed under the Mozilla Public License, version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.mozilla.org/en-US/MPL/2.0/

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operator) DeepCopyInto(out *Operator) {
	*out = *in
	if in.SigningKeys != nil {
		in, out := &in.SigningKeys, &out.SigningKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OperatorServiceURLs != nil {
		in, out := &in.OperatorServiceURLs, &out.OperatorServiceURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.GenericFields.DeepCopyInto(&out.GenericFields)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operator.
func (in *Operator) DeepCopy() *Operator {
	if in == nil {
		return nil
	}
	out := new(Operator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorClaims) DeepCopyInto(out *OperatorClaims) {
	*out = *in
	out.ClaimsData = in.ClaimsData
	in.Operator.DeepCopyInto(&out.Operator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorClaims.
func (in *OperatorClaims) DeepCopy() *OperatorClaims {
	if in == nil {
		return nil
	}
	out := new(OperatorClaims)
	in.DeepCopyInto(out)
	return out
}
