@startmindmap
* nats
** cmd
*** operator
**** <operator>
***** account
****** <account>
******* user
******** <user>
** nkey
*** operator
**** <operator>
***** signing
****** <signingkey>
***** account
****** <account>
******* signing
******** <signingkey>
******* user
******** <user>
** jwt
*** operator
**** <operator>
***** account
****** <account>
******* user
******** <user>

@endmindmap