//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The EdgeFarm Authors.

Licensed under the Mozilla Public License, version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.mozilla.org/en-US/MPL/2.0/

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Account) DeepCopyInto(out *Account) {
	*out = *in
	if in.Imports != nil {
		in, out := &in.Imports, &out.Imports
		*out = make([]Import, len(*in))
		copy(*out, *in)
	}
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]Export, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Limits.DeepCopyInto(&out.Limits)
	if in.SigningKeys != nil {
		in, out := &in.SigningKeys, &out.SigningKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Revocations != nil {
		in, out := &in.Revocations, &out.Revocations
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.DefaultPermissions.DeepCopyInto(&out.DefaultPermissions)
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make(map[string][]WeightedMapping, len(*in))
		for key, val := range *in {
			var outVal []WeightedMapping
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]WeightedMapping, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	out.Info = in.Info
	in.GenericFields.DeepCopyInto(&out.GenericFields)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Account.
func (in *Account) DeepCopy() *Account {
	if in == nil {
		return nil
	}
	out := new(Account)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountClaims) DeepCopyInto(out *AccountClaims) {
	*out = *in
	out.ClaimsData = in.ClaimsData
	in.Account.DeepCopyInto(&out.Account)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountClaims.
func (in *AccountClaims) DeepCopy() *AccountClaims {
	if in == nil {
		return nil
	}
	out := new(AccountClaims)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountLimits) DeepCopyInto(out *AccountLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountLimits.
func (in *AccountLimits) DeepCopy() *AccountLimits {
	if in == nil {
		return nil
	}
	out := new(AccountLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Export) DeepCopyInto(out *Export) {
	*out = *in
	if in.Revocations != nil {
		in, out := &in.Revocations, &out.Revocations
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Latency != nil {
		in, out := &in.Latency, &out.Latency
		*out = new(ServiceLatency)
		**out = **in
	}
	out.Info = in.Info
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Export.
func (in *Export) DeepCopy() *Export {
	if in == nil {
		return nil
	}
	out := new(Export)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Identity) DeepCopyInto(out *Identity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Identity.
func (in *Identity) DeepCopy() *Identity {
	if in == nil {
		return nil
	}
	out := new(Identity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Import) DeepCopyInto(out *Import) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Import.
func (in *Import) DeepCopy() *Import {
	if in == nil {
		return nil
	}
	out := new(Import)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetStreamLimits) DeepCopyInto(out *JetStreamLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetStreamLimits.
func (in *JetStreamLimits) DeepCopy() *JetStreamLimits {
	if in == nil {
		return nil
	}
	out := new(JetStreamLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in JetStreamTieredLimits) DeepCopyInto(out *JetStreamTieredLimits) {
	{
		in := &in
		*out = make(JetStreamTieredLimits, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetStreamTieredLimits.
func (in JetStreamTieredLimits) DeepCopy() JetStreamTieredLimits {
	if in == nil {
		return nil
	}
	out := new(JetStreamTieredLimits)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorLimits) DeepCopyInto(out *OperatorLimits) {
	*out = *in
	out.NatsLimits = in.NatsLimits
	out.AccountLimits = in.AccountLimits
	out.JetStreamLimits = in.JetStreamLimits
	if in.JetStreamTieredLimits != nil {
		in, out := &in.JetStreamTieredLimits, &out.JetStreamTieredLimits
		*out = make(JetStreamTieredLimits, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorLimits.
func (in *OperatorLimits) DeepCopy() *OperatorLimits {
	if in == nil {
		return nil
	}
	out := new(OperatorLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLatency) DeepCopyInto(out *ServiceLatency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLatency.
func (in *ServiceLatency) DeepCopy() *ServiceLatency {
	if in == nil {
		return nil
	}
	out := new(ServiceLatency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserScope) DeepCopyInto(out *UserScope) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserScope.
func (in *UserScope) DeepCopy() *UserScope {
	if in == nil {
		return nil
	}
	out := new(UserScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightedMapping) DeepCopyInto(out *WeightedMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightedMapping.
func (in *WeightedMapping) DeepCopy() *WeightedMapping {
	if in == nil {
		return nil
	}
	out := new(WeightedMapping)
	in.DeepCopyInto(out)
	return out
}
