name: Release

on:
  workflow_run:
    workflows: ["Lint Commit Messages"]
    branches:
      - main
      - beta
    types:
      - completed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go 1.21.10
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.10'

      - name: Run Tests
        run: |
          make test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux', 'windows', 'darwin']
        architecture: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go 1.21.10
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.10'

      - name: Build the artifacts
        run: |
          make OS=${{ matrix.os }} GO_ARCH=${{ matrix.architecture }} build

      - name: uplpoad built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vault-plugin-secrets-nats-${{ matrix.os }}-${{ matrix.architecture }}
          path: build/vault/plugins/vault-plugin-secrets-nats-*
          retention-days: 1
          overwrite: true
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/vault/plugins/
          merge-multiple: true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: siredmar
        run: |-
          #!/bin/bash
          set -e
          npm install @semantic-release/exec @eclass/semantic-release-docker @semantic-release/git -D
          npx -c semantic-release